apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-library-ingress
  namespace: book-library
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: / # Health check path for the ALB
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30" # Health check interval for the ALB
    alb.ingress.kubernetes.io/success-codes: "200,404" # Success codes for the ALB
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-library-service
                port:
                  number: 8000
